export const imgData = [
  {
    id: 1,
    url: "/src/assets/homepage_boy_1.png",
    src: "/src/assets/homepage_img_down.svg",

    alt: "A scenic beach view",
    // width: 1280,
    // height: 720,
  },
  {
    id: 2,
    url: "/src/assets/homepage_girl_1.png",
    src: "/src/assets/homepage_img_down.svg",
    alt: "A dense forest with sunlight peeking through",
    // width: 1920,
    // height: 1080,
  },
  {
    id: 3,
    url: "/src/assets/homepage_boy_2.png",
    src: "/src/assets/homepage_img_down.svg",
    alt: "A city skyline at night",
    width: 1366,
    height: 768,
  },
  {
    id: 4,
    url: "/src/assets/homepage_girl_2.png",
    src: "/src/assets/homepage_img_down.svg",
    alt: "A city skyline at night",
    width: 1366,
    height: 768,
  },
  {
    id: 5,
    url: "/src/assets/homepage_boy_1.png",
    src: "/src/assets/homepage_img_down.svg",
    alt: "A city skyline at night",
    width: 1366,
    height: 768,
  },
  {
    id: 6,
    url: "/src/assets/homepage_boy_3.png",
    src: "/src/assets/homepage_img_down.svg",
    alt: "A city skyline at night",
    width: 1366,
    height: 768,
  },
  // {
  //   id: 7,
  //   url: "/src/assets/homepage_boy_3.png",
  //    src: "/src/assets/homepage_img_down.svg",
  //   alt: "A city skyline at night",
  //   width: 1366,
  //   height: 768,
  // },
  // {
  //   id: 8,
  //   url: "/src/assets/homepage_boy_3.png",
  //    src: "/src/assets/homepage_img_down.svg",
  //   alt: "A city skyline at night",
  //   width: 1366,
  //   height: 768,
  // },
];
